# Generated by Django 2.0.7 on 2018-07-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_transitNum', models.IntegerField()),
                ('account_instNum', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=200)),
                ('account_balance', models.FloatField()),
                ('account_holder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_amount', models.FloatField()),
                ('transaction_time', models.DateTimeField(verbose_name='transaction time')),
                ('transaction_origin', models.IntegerField()),
                ('transaction_destination', models.IntegerField()),
            ],
        ),
    ]
