# Generated by Django 2.0.7 on 2018-07-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0002_transaction_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicbanking.Account'),
        ),
    ]
