# Generated by Django 2.0.7 on 2018-07-21 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0007_auto_20180719_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_destination', to='publicbanking.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_origin', to='publicbanking.Account'),
        ),
    ]
