# Generated by Django 2.0.7 on 2018-07-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0010_auto_20180720_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_destination',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_origin',
            field=models.IntegerField(),
        ),
    ]
