# Generated by Django 2.0.7 on 2018-07-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0004_auto_20180718_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_card',
        ),
    ]
