# Generated by Django 2.0.7 on 2018-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0005_remove_account_account_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_card',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
