# Generated by Django 2.0.7 on 2018-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0011_auto_20180720_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_running_balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
