# Generated by Django 2.0.7 on 2018-07-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0012_transaction_transaction_running_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_running_balance',
        ),
    ]
