# Generated by Django 2.0.7 on 2018-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0013_remove_transaction_transaction_running_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_streetname', models.CharField(max_length=200)),
                ('client_housenum', models.IntegerField()),
                ('client_zipCode', models.CharField(max_length=6)),
                ('client_phone', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=200)),
            ],
        ),
    ]
