# Generated by Django 2.0.7 on 2018-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0015_auto_20180729_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_destination',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_destination',
            field=models.ManyToManyField(related_name='Destination', to='publicbanking.Account'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_origin',
            field=models.ManyToManyField(related_name='Origin', to='publicbanking.Account'),
        ),
    ]
