# Generated by Django 2.0.7 on 2018-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0016_auto_20180729_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_card',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
