# Generated by Django 2.0.7 on 2018-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0017_auto_20180729_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_card',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
