# Generated by Django 2.0.7 on 2018-07-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0018_auto_20180729_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicbanking.Client'),
        ),
    ]
