# Generated by Django 2.0.7 on 2018-07-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0020_auto_20180730_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicbanking.Client'),
        ),
    ]
