# Generated by Django 2.0.7 on 2018-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0022_auto_20180803_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypes',
            name='account_interest_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
