# Generated by Django 2.0.7 on 2018-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0023_auto_20180803_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
