# Generated by Django 2.0.7 on 2018-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0026_auto_20180803_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountTypes',
            new_name='AccountType',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
