# Generated by Django 2.0.5 on 2018-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0028_auto_20180803_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_destination_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_origin_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
