# Generated by Django 2.0.5 on 2018-08-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0029_auto_20180806_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_destination_balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_origin_balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
