# Generated by Django 2.0.5 on 2018-08-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0031_auto_20180812_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiretransaction',
            name='transaction_destination_accountNum',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiretransaction',
            name='transaction_destination_bankAddress',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiretransaction',
            name='transaction_destination_recipient_address',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiretransaction',
            name='transaction_destination_recipient_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiretransaction',
            name='transaction_destination_routingNum',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
