# Generated by Django 2.0.5 on 2018-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbanking', '0033_wiretransaction_transaction_destination_instnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_frequency',
            field=models.CharField(choices=[('ONCE', 'o'), ('DAILY', 'd'), ('WEEKLY', 'w'), ('MONTHLY', 'm')], default='ONCE', max_length=9),
        ),
    ]
